services:
  - type: web
    name: kids-games-backend
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kids-games-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: kids-games-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: kids-games-db
          property: password

databases:
  - name: kids-games-db
    plan: free
