spring.datasource.url=jdbc:postgresql://ep-summer-heart-amjbg69x-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zqJOV0cEwR6K
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
spring.h2.console.enabled=false

jwt.secret=YashiMittaWorld-SuperSecret-Key-MustBe32CharsOrMore!!
jwt.expiration-ms=604800000

server.port=8080
