-- Seed word bank for Word/Spelling Game
INSERT INTO word (word, hint, difficulty) VALUES ('apple', 'A red or green fruit', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('beach', 'Sandy place by the ocean', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('cloud', 'White fluffy thing in the sky', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('dance', 'Move your body to music', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('eagle', 'A large bird of prey', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('flame', 'Fire produces this', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('grape', 'Small purple or green fruit', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('horse', 'Animal you can ride', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('igloo', 'House made of ice', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('juice', 'Drink made from fruit', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('kite', 'Flies in the wind on a string', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('lemon', 'Yellow sour citrus fruit', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('magic', 'Wizards and witches use this', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('night', 'Time when the moon is out', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('ocean', 'Huge body of salt water', 'EASY');
INSERT INTO word (word, hint, difficulty) VALUES ('piano', 'Musical instrument with black and white keys', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('queen', 'Female ruler of a kingdom', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('robot', 'A machine that can do tasks', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('snake', 'A reptile with no legs', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('tiger', 'Orange striped big cat', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('uncle', 'Your parent''s brother', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('violet', 'A shade of purple', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('whale', 'Largest mammal in the ocean', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('xylophone', 'A musical instrument you hit with mallets', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('yogurt', 'Creamy dairy food', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('zebra', 'Black and white striped animal', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('blanket', 'Keeps you warm at night', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('dolphin', 'Smart ocean mammal', 'MEDIUM');
INSERT INTO word (word, hint, difficulty) VALUES ('elephant', 'Largest land animal with a trunk', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('football', 'Sport played with an oval ball', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('giraffe', 'Tallest animal with a long neck', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('hospital', 'Where you go when you are sick', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('invisible', 'Cannot be seen', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('jellyfish', 'Transparent ocean creature', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('knapsack', 'A bag you carry on your back', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('language', 'System of words we use to communicate', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('mountain', 'Very high landform', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('necklace', 'Jewelry worn around the neck', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('orchestra', 'Group of musicians playing together', 'HARD');
INSERT INTO word (word, hint, difficulty) VALUES ('porcupine', 'Spiky animal', 'HARD');
